backend:
  name: git-gateway
  branch: main # or "master" if your repo uses that

media_folder: 'src/assets/img/blog' # where uploaded images are stored in repo
public_folder: '/assets/img/blog' # public URL path to images

collections:
  - name: 'blog'
    label: 'Blog Posts'
    label_singular: 'Blog Post'
    description: 'Manage all blog articles displayed on the site.'
    format: 'json'
    file: 'src/_data/blog.json' # points to your JSON data file
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Posts'
        name: 'posts'
        widget: 'list'
        fields:
          - { label: 'ID', name: 'id', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'datetime', format: 'MMMM DD, YYYY' }
          - { label: 'Author', name: 'author', widget: 'string', default: 'Team ChemGuard' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - label: 'Content'
            name: 'content'
            widget: 'list'
            field:
              label: 'Paragraph'
              name: 'paragraph'
              widget: 'text'
